services:
  - type: web
    name: sbr-agent-ai-backend
    env: docker
    dockerContext: backend
    dockerfilePath: Dockerfile
    plan: starter
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        fromDatabase:
          name: sbr-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: sbr-mongodb
    plan: starter
